@startuml Manage_Reservation_GETONE

title "Manage Reservation (GET One)"

header MasQ Sequence Diagram
footer Page %page% of %lastpage%

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservations
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationsDatabase

client->server ++:req.get('/api/reservations/:id')
server->routerReservations ++:app.use('/api/reservations',reservations)
routerReservations -> controllersReservations ++:getReservation()

controllersReservations->modelReservation ++:findById(req.params.id)
modelReservation ->ReservationsDatabase ++: ReservationSchema
ReservationsDatabase --> modelReservation --: reservation
controllersReservations <-- modelReservation --:reservation

controllersReservations->client --:response

@enduml
